[tool.poetry]
name = "celerymon"
version = "0.1.3"
description = ""
authors = ["Masaya Suzuki <masaya@aviator.co>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
celery = { version = "^5.3.4", extras = ["redis"] }
prometheus-client = "^0.20.0"

[tool.poetry.scripts]
celerymon = 'celerymon.cli:run'

[tool.poetry.group.dev.dependencies]
celery-types = "^0.22.0"
mypy = "^1.5.1"
types-redis = "^4.6.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
